Repository kookmin-sw/capstone-2020-1, pull requests merged in 2020-04, with the labels that each got.

#17 404 리턴 버그 수정 필요 #16
  src/server/settings/logger.py
  src/server/settings/wsgi.py
Labels: bug

#21 Frontend frame
  src/web/src/backgroundImage.jpg
  src/web/src/component/Description.js
  src/web/src/component/InputUrl.js
  src/web/src/component/Login.js
  src/web/src/component/Navibar.js
  src/web/src/component/Result.js
  src/web/src/page/MainPage.js
  src/web/src/yoba_logo.png
  src/web/yarn.lock
Labels: enhancement

#27 Frontend frame
  src/web/src/App.js
  src/web/src/backgroundImage.jpg
  src/web/src/component/Description.js
  src/web/src/component/InputUrl.js
  src/web/src/component/Login.js
  src/web/src/component/Navibar.js
  src/web/src/component/Result.js
  src/web/src/page/MainPage.js
  src/web/src/yoba_logo.png
  src/web/yarn.lock
Labels: enhancement

#30 Move files to proper folders
  src/analyze/analysis.py
  src/analyze/volume_extract.py
  src/download/audio.py
  src/download/chatlog.py
  src/download/video.py
  src/proof/README.md
  src/proof/loop.py
  src/proof/main.py
Labels: enhancement

#31 유저 정보 테이블 생성
  .gitignore
  src/server/alembic.ini
  src/server/api/models/user_info.py
  src/server/migrations/env.py
  src/server/migrations/script.py.mako
  src/server/migrations/versions/9c357a42abd7_init_user_info.py
  src/server/settings/settings.py
Labels: enhancement

#34 Frontend login signup
  src/web/src/App.js
  src/web/src/component/Description.js
  src/web/src/component/InputUrl.js
  src/web/src/component/Login.js
  src/web/src/component/Navibar.js
  src/web/src/page/MainPage.js
Labels: enhancement

#40 Frontend login signup
  src/web/src/component/Login.js
  src/web/src/component/SignUp.js
Labels: enhancement

#41 Frontend result graph mocking
  src/web/src/component/Highlight.js
  src/web/src/component/InputUrl.js
  src/web/src/component/Result.js
  src/web/src/component/ViewerRank.js
  src/web/src/component/ViewerReact.js
  src/web/src/page/MainPage.js
Labels: enhancement

#54 채팅로그에서 상위 10개 키워드 추출 api 추가
  .gitignore
  src/server/api/chatlog.py
  src/server/settings/wsgi.py
Labels: enhancement

#56 채팅로그에서 상위 10개 키워드 추출 api 개선
  src/server/api/chatlog.py
  src/server/tests/test_chatlog.py
Labels: test
